% % Script to analyse synthetic SDLT data with SDLT model.

% Switch on debugger.
dbstop if error

% Adding folders to path, clearing workspace and closing all figure windows.
addpath guifiles Borrowing  
clear all
close all

% Parameters to be used in analysis.
GlobalSwitches
GlobalValues

% Input struct.
fsu = struct(...
    'BETA', rand, ...  % Borrowing rate.
    'BORROW', 0, ...    % Not used.
    'BORROWFRAC', 0, ...
    'BORROWING', 1, ... % Borrowing on?
    'CLADEAGESMASK', [], ...
    'CLADEMASK', [], ...
    'COLUMNMASK', [], ...
    'DATAFILE', 'Data/SIM_B.nex', ...
    'DATAMASK', [], ... % Taxa to be excluded from analysis, [] to include all.
    'DATASOURCE', 1, ...    % 1 = NEXUS, 2 = BUILD; possibly depracated.
    'DATASYN', 0, ...	% 1 if data is synthetic, 0 otherwise.
    'DEPNU', 1, ...
    'DONTMOVECATS', 0, ...
    ... % Green's functions approach.
    'GF_START', 25, ... % If we use Green's functions approach, at what what number of branches should we start using it?
    'GF_APPROX', 1, ... % At what distance should we truncate sum over Green's Functions solutions.
    ... % End of Green's functions approach.
    'GUICONTENT', [], ...
    'ISCOLMASK', 0, ...
    'ISCLADE', 1, ...   % Clades on?
    'ISLRRANDOM', 1, ...
    'KAPPA', 0.1, ...   % Affects catastrophe duration.
    'KNOWCATS', 0, ...
    'LAMBDA', 1, ...	% Birth rate, integrated out.
    'LOCALBORROW', 0, ...
    'LOSSRATE', 0.2, ...
    'LOSSRATEBRANCHVAR', 0, ...
    'LOSSRATECLASSVAR', 0, ...
    'LOST', 0, ...  % Throw out data that did not survive into more than LOST leaves.
    'LOSTONES', 0, ...
    'MASKING', 0, ...   % Exclude taxa in DATAMASK?
    'MAXDIST', 16000, ...
    'MCMCCAT', 1, ...   % Catastrophes on?
    'MCMCINITBETA', 0.001, ...  % Initial beta.
    'MCMCINITKAPPA', 0.5, ...   % Initial kappa.
    'MCMCINITLAMBDA', 1, ...    % Initial lambda.
    'MCMCINITMU', 0.001, ... % Initial mu.
    'MCMCINITNU', 55, ...
    'MCMCINITP', 1, ...
    'MCMCINITRHO', 0.00015, ... % Initial rho.
    'MCMCINITTHETA', 0.01, ...  % Initial theta.
    'MCMCINITTREE', [], ...
    'MCMCINITTREEFILE', [], ... % OLDSTART, 'filename.nex' - include full path if not in current directory.
    'MCMCINITTREENUM', 0, ...   % OLDSTART, line no. of tree in MCMCINITTREEFILE.
    'MCMCINITTREESTYLE', 2, ... % TRUSTART 1, EXPSTART 2, OLDSTART 3.
    'MCMCMISS', 1, ...      % Include xi's, missing data, etc?
    'MCMCVARYTOP', 1, ...   % Allow topology to change?
    'MISDAT', 1, ...    % 1, as we want to include missing data in likelihood. % discrepancy between LogLkd and logLkd2 when switched off.
    'NMEANINGCLASS', 2, ...
    'NU', 3, ...
    'NUMSEQ', 10, ...    % Number of species under investigation.
    'NUMSYNTHCLADES', 0, ...
    'OUTFILE', 'SIM_B_B', ...
    'OUTPATH', 'Output/', ...
    'POLYMORPH', 0, ...
    'PSURVIVE', 1, ...
    'RANDOMKAPPA', 0, ...
    'RANDOMRHO', 0, ...
    'RHO', 0.01, ...        % Rate at which catastrophes occur.
    'ROOTMAX', 2000, ...   % Fairly loose maximum root age.
    'RUNLENGTH', 1e6, ... % Number of iterations to perform.
    'SEED', floor(now ./ rem(now, 1)), ...  % Seed to use.
    'SEEDRAND', 1, ...  % Seed random numbers?
    'STRONGCLADES', [], ... % Set to 1 below if there are clades imposed.
    'SUBSAMPLE', 1e2, ...    % Thin to every kth iteration.
    'SYNTHCLADES', 0, ...
    'SYNTHCLADESACCURACY', 0, ...
    'SYNTHCLADESTIMES', 0, ...
    'SYNTHSTYLE', 2, ...
    'SYNTHTRE', 1, ...
    'SYNTHTREFILE', '', ...
    'THETA', 0.01, ...  % Exponential branching rate.
    'TOPOLOGYPRIOR', 2, ... % LABHIST = 1, TOPO = 2.
    'TREEPRIOR', 2, ...     % YULE = 1, FLAT = 2.
    'VARYBETA', 1, ...  % Allow beta to vary?
    'VARYKAPPA', 1, ... % Allow kappa to vary?
    'VARYLAMBDA', 0, ...    % Allow lambda to vary?
    'VARYMU', 1, ...    % Allow mu to vary?
    'VARYNU', 0, ...
    'VARYP', 0, ...
    'VARYRHO', 0, ...   % Allow rho to vary?
    'VERBOSE', 1, ...   % Display output.
    'VOCABSIZE', 0);

% Always using strong clades if there are clades.
if fsu.ISCLADE == 1; fsu.STRONGCLADES = 1; end

% Add data from intput file to fsu struct, include true data if it exists.
[s, fsu.GUICONTENT, fsu.GUITRUE, fsu.CLADE] = nexus2stype(fsu.DATAFILE);
if ~isempty(s); fsu.GUITRUE.state.tree = s; end

% Perform MCMC.
runmcmc(fsu);
