function state = dummyState()
    % Only set necessary fields
    state = struct('lambda',  rand, ...
                   'mu', rand, ...
                   'beta', rand, ...
                   'kappa', 0.25 + rand * 0.75, ...
                   'rho', rand);
    state.nu = state.lambda * state.kappa / state.mu;
    state.nodes = 1:6;
end
