function coupled = checkCoupling(state_x, state_y)
    % TODO: Check catastrophes
    coupled = state_x.logprior == state_y.logprior ...
        && state_x.beta == state_y.beta ...
        && state_x.loglkd == state_y.loglkd ...
        && state_x.mu == state_y.mu ...
        && all([state_x.tree.time] == [state_y.tree.time]) ...
        && equaltrees(state_x.tree, state_y.tree);

    % TODO: change after further checks
    if coupled && ~checkCouplingExtra(state_x, state_y)
        warning('Some state fields do not match');
    end
end
