function [newage_x, newage_y, logq_x, logq_y] = sampleCoupling(i, j_x, j_y, ...
        k_x, k_y, s_x, s_y, THETA)

    global ROOT

    if s_x(j_x).type == ROOT
        % If j_x is the root in x then j_y = j_x and is the root in y
        jT_x = s_x(j_x).time;
        jT_y = s_y(j_y).time;
        [newage_x, newage_y] ...
            = maximalCouplingShiftedExponential(jT_x, jT_y, THETA);
        logq_x = BchooseCoupledMaximal.sampleCoupling.getCoupling1Parameter(...
            i, jT_x, s_x, newage_x, THETA);
        logq_y = BchooseCoupledMaximal.sampleCoupling.getCoupling1Parameter(...
            i, jT_y, s_y, newage_y, THETA);
    else
        % logq depends on whether iP is the root or not
        [new_minage_x, kT_x, logq_x] ...
            = BchooseCoupledMaximal.sampleCoupling.getCoupling2Parameters(i, ...
                j_x, k_x, s_x, THETA);
        [new_minage_y, kT_y, logq_y] ...
            = BchooseCoupledMaximal.sampleCoupling.getCoupling2Parameters(i, ...
                j_y, k_y, s_y, THETA);
        [newage_x, newage_y] ...
            = maximalCouplingUniform(new_minage_x, kT_x, new_minage_y, kT_y);
    end
end
