% Parallelised fast binary-to-decimal function.
mex -IBorrowing -outdir Borrowing ...
    Borrowing/fastBi2De_c_par.c ...
    CFLAGS="\$CFLAGS -fopenmp -O3 -std=c11 -march=native" ...
    LDFLAGS="\$LDFLAGS -fopenmp"

% Parallelised fast decimal-to-binary function.
mex -IBorrowing -outdir Borrowing ...
    Borrowing/fastDe2Bi_c_par.c ...
    CFLAGS="\$CFLAGS -fopenmp -O3 -std=c11 -march=native" ...
    LDFLAGS="\$LDFLAGS -fopenmp"